package dialogue;

public class Reviews {

    public String[] lowReviews = {"I'm pretty sure my burger was just two pieces of cardboard slapped together with some ketchup in the middle.", "The only thing that could have made my burger worse is if it had come with a side of food poisoning.", "I'm not convinced that the 'meat' in my burger was actually meat.", "I would have been better off just eating the napkin that came with my burger.", "The only thing that made my burger remotely edible was drowning it in ketchup and mustard.", "I would rather eat a shoe than come back to this place again.", "I have a newfound appreciation for hospital food after eating here.", "I'm pretty sure the lettuce on my burger was just shredded packing material.", "This burger was so bad, I think I lost a year off my life just by eating it.", "If I wanted a hockey puck, I would have gone to the sporting goods store instead."};
    
    public String[] mediumLowReviews = {"I've had better burgers at a gas station, but at least the paper bag they came in was sturdy.", "The burgers were so dry, I needed a gallon of water just to wash them down.", "I ordered a burger and got a hockey puck with cheese on it. I guess they were going for a sporty theme?", "I'm pretty sure the 'lettuce' on my burger was just shredded cardboard.", "I asked for medium rare and got well done, but hey, at least it was cooked.", "I wouldn't say the burgers were bad, but I did have to fight off a pack of seagulls to keep them.", "The buns were stale, the meat was flavorless, and the toppings were MIA. But hey, they got my order right.", "I'm not sure what was in my burger, but I'm pretty sure it wasn't beef. Or any kind of meat, for that matter.", "If you like your burgers well-done and your expectations low, this is the place for you.", "I think I found a piece of the restaurant's health code violation in my burger. At least it added some much-needed crunch."};

    public String[] mediumHighReviews = {"The burgers here are pretty good, but the fries are just average. If you're looking for a quick bite, this place will do the trick.", "I was pleasantly surprised by the burgers here. They're not gourmet by any means, but they hit the spot.", "The burgers are definitely worth a try, but the atmosphere could use some work. It's not the most comfortable place to dine in.", "This place serves up some tasty burgers. The only downside is the wait can be a bit long during peak hours.", "I've been here a few times and have always enjoyed the burgers. The staff is friendly and the prices are fair.", "Solid burgers and decent service. It's not my favorite burger joint, but I wouldn't hesitate to come back.", "The burgers are fresh and juicy, but the sides could use some improvement. Overall, a decent spot for a quick meal.", "The burgers here are definitely above average, but I wish there were more toppings to choose from. Still, a satisfying meal.", "The burgers are cooked perfectly and the portions are generous. It's a bit of a no-frills place, but the food makes up for it.", "This place is a hidden gem for burger lovers. The prices are reasonable and the burgers are top-notch. I'll definitely be back!"};

    public String[] highReviews = {"I had a religious experience with their burgers. My taste buds are forever changed.", "I never knew a burger could bring me so much joy. I might just marry their bacon cheeseburger.", "If heaven had a burger joint, this would be it. Hands down the best burgers I've ever had.", "I want to keep this place a secret, but their burgers are too good not to share. 10/10 would recommend.", "I've been searching for the perfect burger my whole life, and I've finally found it. This place is a hidden gem.", "I'm convinced that their secret sauce is made of magic. I've never tasted anything so delicious in my life.", "I don't normally write reviews, but this place deserves all the praise. Their burgers are out of this world.", "I don't know what kind of sorcery they use to make their buns so soft, but I need to know their secret.", "If I had to choose between this burger joint and a fancy restaurant, I'd pick this place every time. It's that good.", "I never knew a burger could bring me to tears, but that's how good their burgers are. Don't miss out on this gem."};
    
}
